print("\n")
print("\t \t \t Batamindo", end=" ")
print("Industrial", end=" ")
print("Park", end=" ")
print("\n =========================================================================================================================")
print("\n \t \t \t   Profil Perusahaan")
print("\n Nama Lengkap Perusahaan \t : Batamindo Industrial Park")
print("\n Alamat Perusahaan       \t : Gedung Wisma Batamindo.Jl.Rasamala 1 Kawasan Industri Batamindo Muka Kuning - Batam 29443")
print("\n Pemimpin Perusahaan     \t : Mook Sooi Wah")
print("\n =========================================================================================================================")
