print("\n")
print("\t \t \t Karimun", end=" ")
print("Maju", end=" ")
print("Jaya", end=" ")
print("\n =========================================================================================================================")
print(" \t \t \t   Profil Toko")
print("\n Nama Toko    \t : Karimun Maju Jaya")
print("\n Alamat Toko  \t : JL. Teluk Air")
print("\n Jenis Toko   \t : Toko Sembako")
print("\n Pemilik Toko \t : Muhamad Zulfikar")
print("\n =========================================================================================================================")
